### ISSUE TITLE
How to convert EfficientNet Lite to TF Lite

### ISSUE THREAD

**Issue by CaptainDario** [sebastian-sz/efficientnet-lite-keras#12]
When I try to convert this to TF Lite with:
```
converter = tf.lite.TFLiteConverter.from_keras_model(eff_net_lite)
tflite_model = converter.convert()
```
I get an error:
```
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: AddV2, BiasAdd, Cast, Conv2D, DepthwiseConv2dNative, FusedBatchNormV3, MatMul, Mean, Pad, Relu6, Softmax
Details:
	tf.AddV2 {device = ""}
	tf.BiasAdd {data_format = "NHWC", device = ""}
	tf.Cast {Truncate = false, device = ""}
	tf.Conv2D {data_format = "NHWC", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "SAME", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true}
	tf.Conv2D {data_format = "NHWC", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 2, 2, 1], use_cudnn_on_gpu = true}
	tf.DepthwiseConv2dNative {data_format = "NHWC", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "SAME", strides = [1, 1, 1, 1]}
	tf.DepthwiseConv2dNative {data_format = "NHWC", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 2, 2, 1]}
	tf.FusedBatchNormV3 {data_format = "NHWC", device = "", epsilon = 1.000000e-03 : f32, exponential_avg_factor = 1.000000e+00 : f32, is_training = false}
	tf.MatMul {transpose_a = false, transpose_b = true}
	tf.Mean {device = "", keep_dims = false}
	tf.Pad {device = ""}
	tf.Relu6 {device = ""}
	tf.Softmax {device = ""}
```

Like the messages says I can include `SELECT_TF_OPS`:
```
converter = tf.lite.TFLiteConverter.from_keras_model(eff_net_lite)

converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]

tflite_model = converter.convert()
```

With this everything works however the model size gets much bigger which is not desirable for edge devices.

Is this the only way of getting it to work? Or am I missing something?

**Comment by sebastian-sz** [comment]
Hi, this is strange, the TFLite conversion should work out of the box.

Can you tell me:

1. What is the Tensorlfow version you are using? (`tf.__version__`)
2. Is the code for `eff_net_lite`, more or less, as follows?
```python
eff_net_lite = EfficientNetLiteB0(
    include_top=True,
    weights=None,
    input_shape=(64, 64, 1),
    classes=6543,
    pooling="max",
    classifier_activation="softmax"
)
```
Please, let me know!
Sebastian

**Comment by CaptainDario** [comment]
>     1. What is the Tensorlfow version you are using? (`tf.__version__`)

>>> tensorflow.__version__
'2.5.0'

>     2\. Is the code for `eff_net_lite`, more or less, as follows?
Not only more or less it is exactly like that. I am still trying to get the model from the other issue to work.

**Comment by CaptainDario** [comment]
The beginning of the stace track:
```
Exception                                 Traceback (most recent call last)
E:\projects\DaKanjiRecognizerML\.venv\lib\site-packages\tensorflow\lite\python\convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    290     try:
--> 291       model_str = wrap_toco.wrapped_toco_convert(model_flags_str,
    292                                                  toco_flags_str, input_data_str,

E:\projects\DaKanjiRecognizerML\.venv\lib\site-packages\tensorflow\lite\python\wrap_toco.py in wrapped_toco_convert(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
     31   """Wraps TocoConvert with lazy loader."""
---> 32   return _pywrap_toco_api.TocoConvert(
     33       model_flags_str,

Exception: E:\projects\DaKanjiRecognizerML\.venv\lib\site-packages\tensorflow\python\keras\engine\functional.py:420:0: error: 'tf.Cast' op is neither a custom op nor a flex op
E:\projects\DaKanjiRecognizerML\.venv\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:1030:0: note: called from
```

Seems like tf.Cast is causing a problem...

**Comment by CaptainDario** [comment]
I setup a [colab notebook](https://colab.research.google.com/drive/1iHlT8CZEHsn66PsKhS3YQPGgKObQvpbp?usp=sharing) to reproduce this.

**Comment by CaptainDario** [comment]
It seems like it is related to the mixed_precision.

**Comment by CaptainDario** [comment]
Deploying the model in this way leads to abysmal performance on GPU (CPU is fine though).
Inference time for 64x64 images are between 1 and 2 seconds.

**Comment by sebastian-sz** [comment]
Hi, thanks for the Colab so I can reproduce the error - at first glance, it seems to be a problem with Tensorflow. Please, give me some time and I will try to look into this today.

**Comment by sebastian-sz** [comment]
@CaptainDario Hi, big thank you for the reproducible Colab - at first glance this seems like a problem with Tensorflow. Please give me some more time and I will try to look into this (and the previous) issue today.

**Comment by sebastian-sz** [comment]
@CaptainDario Hi, I could reproduce the issue with the Colab you provided. I have the following insights:

### Why this throws error:
The model conversion throws error becuase Tensorflow does not allow to convert models to TFLite (at least not directly), trained with mixed precision policy. There is even an issue, [here](https://github.com/tensorflow/tensorflow/issues/46380) on TF official repository. 

This cannot be solved on the level of my repository, but it needs to be fixed in Tensorflow itself.   

Possible workaround that I use, in this case is:
1. Train the model with mixed precision policy (`mixed_float16`)
2. Save only the model weights `model.save_weights` in `.h5` format.
3. Change policy to `float32` and recreate the model with random weights.
4. Load the previously saved weights (`model.load_weights`)
5. Export to TFLite as usual.

As I mentioned, this is an issue in Tensorflow, and apart from this workaround I cannot suggest any other changes. 
You can still train the models in fp16 as long as you load and export them in fp32.
### No need to use TFLITE_BUILTINS and SELECT_TF_OS
When converting the models with policy `float32` you also do not need to use:
```python
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
```
I had success converting your model in both scenarios:

```python
import tensorflow as tf
from efficientnet_lite import EfficientNetLiteB0

# Make sure the policy is tflite compatible = float32
policy = tf.keras.mixed_precision.Policy('float32')
tf.keras.mixed_precision.set_global_policy(policy)

# Create model
eff_net_lite = EfficientNetLiteB0(
    include_top=True,
    weights=None,
    input_shape=(64, 64, 1),
    classes=6543,
    pooling="max",
    classifier_activation="softmax"
)

# Export default tflite:
converter = tf.lite.TFLiteConverter.from_keras_model(eff_net_lite)
tflite_model = converter.convert() # Works

# Export tflite half precision:
converter = tf.lite.TFLiteConverter.from_keras_model(eff_net_lite)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
tflite_model = converter.convert()  # Works.
```

Let me know if this helped!

**Comment by CaptainDario** [comment]
@sebastian-sz thanks for the work around. It is working for me!
Because selecting the TF ops made it work I somehow thought the issue lies somewhere else.

The [solution there](https://github.com/tensorflow/tensorflow/issues/46380#issuecomment-789377374) is also working fine for me. 
For me it is very frustrating that the conversion does not work because I am targeting float16 quantization anyways...

Thanks again for your help! Your EfficientNet Lite will now power one more on device machine learning app.
