### ISSUE TITLE
efficientnet lite to finetune on custom data

### ISSUE THREAD

**Issue by ameyparanjape** [sebastian-sz/efficientnet-lite-keras#3]
Thank you for this contribution! I want to finetune efficientnet-lite model for my custom data. I followed the steps provided to get weights and convert them into `.h5` files for B0-B4.
I am aware of your [PR](https://github.com/tensorflow/tensorflow/pull/48400#issue-611430800), but I was wondering if I can use the current weights from this repo to finetune models on custom data at this stage?

**Comment by sebastian-sz** [comment]
Hi, yes the finetuning should work the same way as for other models in `tf.keras.applications`.  
I added [example in the readme](https://github.com/sebastian-sz/efficientnet-lite-keras#fine-tune-on-custom-data) on how to convert and load the weights for fine tuning. For the rest you could follow the Tensorflow tutorial but use the imported model instead of tutorial's MobilenetV2.

Other variants should also be convertible, but you would have to change the `model` and `ckpt` flag in the conversion script accordingly.

Let me know if this helps.

**Comment by ameyparanjape** [comment]
Thank you @sebastian-sz for the example. I think I was trying to run it outside of the docker before, my bad! I can confirm that it works on docker. I have a follow up question/doubt that I cannot use this currently on my machine without docker, right? I tried that and it gave me this error:
`TypeError: ('Invalid keyword argument: %s', 'lite')`

I am assuming that this is because the PR is still not merged by the tensorflow team. Correct me if I'm wrong about any of this!

**Comment by ameyparanjape** [comment]
I think I figured it out. Here are the steps to enable custom data finetuning (if anyone is interested):
1) In the docker environment - Create a `no-top` base_model (follow [this](https://github.com/sebastian-sz/efficientnet-lite-keras#fine-tune-on-custom-data)), then add custom top layers on base_model depending on your needs and number of classes, activations etc. Compile this model with appropriate params and save this model.
2) This saved model can be used as any other saved model in `tf.keras` environment using `load_model()` method.
3) You will get this: `ValueError: Unknown activation function:relu6`. To get rid of this, define `relu6` as defined in this repo and use it as a `CustomObjectScope`

**Comment by sebastian-sz** [comment]
@ameyparanjape Glad to hear that you figured it out. I was not aware of the problems with Relu6. Perhaps it should be defined as `tf.keras.layers.Relu(6)` instead of custom function. I will be looking into that.

**Comment by sebastian-sz** [comment]
@ameyparanjape Sorry to bother you again. I just wanted to mention that:
1. Thank you for finding this loading error with `ValueError: Unknown activation function:relu6` 
2. I just pushed changes which should fix it so there is no need to call `CustomObjectScope` anymore.

All the best!
