### ISSUE TITLE
Doc | efficientnet_lite_keras_original_outputs | OS error

### ISSUE THREAD

**Issue by reddy75** [sebastian-sz/efficientnet-lite-keras#51]
Hello,
I tried jupyter notebook '**efficientnet_lite_keras_original_outputs.ipynb**' and it end up with error in step **7**:

`2023-03-16 19:00:07.548478: W tensorflow/c/c_api.cc:291] Operation '{name:'efficientnet-lite0/head/dense/bias/Assign' id:1997 op device:{requested: '', assigned: ''} def:{{{node efficientnet-lite0/head/dense/bias/Assign}} = AssignVariableOp[_has_manual_control_dependencies=true, dtype=DT_FLOAT, validate_shape=false](efficientnet-lite0/head/dense/bias, efficientnet-lite0/head/dense/bias/Initializer/zeros)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.
Traceback (most recent call last):
  File "/home/reddy/coral/TensorFlow/workspace/test/efficientnet-lite-keras/docs/tpu/models/official/efficientnet/lite/../export_model.py", line 164, in <module>
    app.run(main)
  File "/home/reddy/.conda/envs/tf2-mm-py39/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/reddy/.conda/envs/tf2-mm-py39/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/reddy/coral/TensorFlow/workspace/test/efficientnet-lite-keras/docs/tpu/models/official/efficientnet/lite/../export_model.py", line 121, in main
    restore_model(sess, FLAGS.ckpt_dir, FLAGS.enable_ema)
  File "/home/reddy/coral/TensorFlow/workspace/test/efficientnet-lite-keras/docs/tpu/models/official/efficientnet/lite/../export_model.py", line 64, in restore_model
    saver.restore(sess, checkpoint)
  File "/home/reddy/.conda/envs/tf2-mm-py39/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 1403, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[7], line 7
      3 get_ipython().system('mkdir outputs')
      5 get_ipython().system('python ../export_model.py        --model_name=$model        --ckpt_dir=/content/tpu/models/official/efficientnet/lite/$model/        --output_saved_model_dir outputs/stuff/        --image_size $shape        --output_tflite=outputs/stuff.tflite        --quantize=False')
----> 7 loaded = tf.saved_model.load("outputs/stuff")
      9 img = tf.image.decode_jpeg(tf.io.read_file("panda.jpg"))
     10 img = tf.image.resize(img, (shape, shape))

File ~/.conda/envs/tf2-mm-py39/lib/python3.9/site-packages/tensorflow/python/saved_model/load.py:828, in load(export_dir, tags, options)
    826 if isinstance(export_dir, os.PathLike):
    827   export_dir = os.fspath(export_dir)
--> 828 result = load_partial(export_dir, None, tags, options)["root"]
    829 return result

File ~/.conda/envs/tf2-mm-py39/lib/python3.9/site-packages/tensorflow/python/saved_model/load.py:933, in load_partial(export_dir, filters, tags, options)
    928 if tags is not None and not isinstance(tags, set):
    929   # Supports e.g. tags=SERVING and tags=[SERVING]. Sets aren't considered
    930   # sequences for nest.flatten, so we put those through as-is.
    931   tags = nest.flatten(tags)
    932 saved_model_proto, debug_info = (
--> 933     loader_impl.parse_saved_model_with_debug_info(export_dir))
    935 if (len(saved_model_proto.meta_graphs) == 1 and
    936     saved_model_proto.meta_graphs[0].HasField("object_graph_def")):
    937   metrics.IncrementReadApi(_LOAD_V2_LABEL)

File ~/.conda/envs/tf2-mm-py39/lib/python3.9/site-packages/tensorflow/python/saved_model/loader_impl.py:57, in parse_saved_model_with_debug_info(export_dir)
     44 def parse_saved_model_with_debug_info(export_dir):
     45   """Reads the savedmodel as well as the graph debug info.
     46 
     47   Args:
   (...)
     55     parsed. Missing graph debug info file is fine.
     56   """
---> 57   saved_model = parse_saved_model(export_dir)
     59   debug_info_path = file_io.join(
     60       saved_model_utils.get_debug_dir(export_dir),
     61       constants.DEBUG_INFO_FILENAME_PB)
     62   debug_info = graph_debug_info_pb2.GraphDebugInfo()

File ~/.conda/envs/tf2-mm-py39/lib/python3.9/site-packages/tensorflow/python/saved_model/loader_impl.py:115, in parse_saved_model(export_dir)
    113     raise IOError(f"Cannot parse file {path_to_pbtxt}: {str(e)}.")
    114 else:
--> 115   raise IOError(
    116       f"SavedModel file does not exist at: {export_dir}{os.path.sep}"
    117       f"{{{constants.SAVED_MODEL_FILENAME_PBTXT}|"
    118       f"{constants.SAVED_MODEL_FILENAME_PB}}}")

OSError: SavedModel file does not exist at: outputs/stuff/{saved_model.pbtxt|saved_model.pb}

`

**Comment by sebastian-sz** [comment]
Hi @reddy75. Thank you for the issue - this notebook is indeed a bit stale. 

I'll try to take a look at it in the next few days.

**Comment by sebastian-sz** [comment]
Hi @reddy75
I cannot reproduce the issue. I just rerun the notebook in Google Colab and it successfully recreated the outputs:
![colab_outputs](https://user-images.githubusercontent.com/58402418/226689062-03638556-cbcb-49eb-8d23-ced01447cdaa.png)



I am using Tensorflow 2.11, are you also using Tensorflow 2.x?
It looks like it fails to create a Tensorflow Saved Model at `outputs/stuff` can you verify that the model gets created at least for a single variant?

**Comment by reddy75** [comment]
Hi @sebastian-sz 
I don't use Google Colab, I was trying to run directly on my laptop.
My setup is:
OS Fedora 36
Python 3.9 in virtual env (conda)
TF 2.5

**Comment by reddy75** [comment]
I also tried install new virtual env with TF2.11, but same result.
I am just guessing, it's possible some packages I am missing against pre-installed in Google Colab.
Can you please share list of your all installed packages from Google Colab?

**Comment by sebastian-sz** [comment]
@reddy75 Ok, I found the issue. 

The notebook was written to work primarly in Colab environment, where the working directory is mounted at `/content/`. 

The notebook will work if you change all occurences of `/content/` to some other directory. E.g. this cell works for me locally:  
(make sure to provide your `SAVE_DIR`):
```python
SAVE_DIR = "/home/<user>/<your>/<path>/<to>/<outputs>"

for model, shape in MODELS:
    !mkdir outputs
    !python ../export_model.py \
      --model_name=$model \
      --ckpt_dir=$model/ \
      --output_saved_model_dir outputs/stuff/ \
      --image_size $shape \
      --output_tflite=outputs/stuff.tflite \
      --quantize=False

    loaded = tf.saved_model.load("outputs/stuff")

    img = tf.image.decode_jpeg(tf.io.read_file("panda.jpg"))
    img = tf.image.resize(img, (shape, shape))
    img = (img - 127.00) / 128.00
    img = tf.expand_dims(img, axis=0)

    out = loaded.signatures['serving_default'](img)

    out_name = f"{SAVE_DIR}/b{model[-1]}_lite_output_{shape}.npy"
    np.save(out_name, out['output'].numpy())

    !rm -r outputs
```
Python 3.9, Tensorflow: 2.11.

**Comment by reddy75** [comment]
Hello @sebastian-sz,
great, according to your explanation it worked as expected.

Thank you.

Current issue can be closed as resolved.

**Comment by sebastian-sz** [comment]
Thanks!
